import { GM_configStruct } from './GM_config_TS/gm_config';
import type { SC2DataManager } from "../ml/SC2DataManager";
import type { ModUtils } from "../ml/Utils";
import type { LogWrapper } from "../ml/ModLoadController";
import { LoadingProgress } from "./LoadingProgress";
import { PassageTracer } from "./PassageTracer";
import { DebugExport } from "./DebugExport";
import { ModLoadSwitch } from "./ModLoadSwitch";
import { ModSubUiAngularJsService } from "./ModSubUiAngularJsService";
import { ModManagerSubUi } from "./ModManagerSubUi";
export declare class Gui {
    gSC2DataManager: SC2DataManager;
    gModUtils: ModUtils;
    gLoadingProgress: LoadingProgress;
    gPassageTracer: PassageTracer;
    thisWin: Window;
    static rIdP: number;
    rId(): string;
    protected debugExport: DebugExport;
    protected modLoadSwitch: ModLoadSwitch;
    protected logger: LogWrapper;
    constructor(gSC2DataManager: SC2DataManager, gModUtils: ModUtils, gLoadingProgress: LoadingProgress, gPassageTracer: PassageTracer, thisWin: Window);
    protected nowModName?: string;
    protected isHttpMode: boolean;
    protected rootNode?: HTMLDivElement;
    protected gui?: GM_configStruct;
    protected logShowConfig: {
        noInfo: boolean;
        noWarning: boolean;
        noError: boolean;
    };
    createGui(): Promise<void>;
    private getLoadLogHtml;
    getModSubUiAngularJsService(): ModSubUiAngularJsService;
    protected modSubUiAngularJsService: ModSubUiAngularJsService;
    protected modManagerSubUi: ModManagerSubUi;
    protected initOk: boolean;
    protected init(): void;
    protected startBanner?: HTMLDivElement;
    loadAndAddMod(htmlFile: HTMLInputElement): Promise<string>;
    listSideLoadMod2(): Promise<string[]>;
    listSideLoadModNameOnly(): Promise<string[]>;
    listSideLoadModNameCanUnload(): Promise<string[]>;
    listSideLoadHiddenModNameOnly(): Promise<string[]>;
    getModListString(): string[];
    getModTReadMe(name: string): Promise<string>;
    getModTJson(name: string): Promise<string>;
    patchHtmlNodeVersionString(gameVersionDisplayNode: HTMLElement | Element | undefined | null): void;
    patchVersionString(): void;
}
