import xxhash from "xxhash-wasm";
import { FileMeta, ModMeta } from "./ModMeta";
import { ModPackFileReaderInterface } from "./ModPackFileReaderInterface";
export declare function XxHashH64Bigint2String(h64: bigint): string;
export declare function XxHashH32Number2String(h32: bigint): string;
export declare function calcXxHash64(data: Uint8Array, xxhashApi: Awaited<ReturnType<typeof xxhash>>): bigint;
export declare function covertFromZipMod(modName: string, filePathList: string[], fileReaderFunc: (filePath: string) => Promise<Uint8Array | undefined>, password?: string | undefined, progressCallback?: (progress: number) => any | Promise<any>, bootFilePath?: string): Promise<{
    modMeta: ModMeta;
    modPackBuffer: Uint8Array<ArrayBuffer>;
    ext: string;
    hash: bigint;
    hashString: string;
}>;
export declare class ModPackFileReader implements ModPackFileReaderInterface {
    constructor();
    get isInit(): boolean;
    private password?;
    private modMeta;
    private fileDataStartPos;
    private xchacha20Key?;
    private xchacha20Nonce?;
    private modPackBuffer;
    private fileTree?;
    static xxhashApi?: Awaited<ReturnType<typeof xxhash>>;
    private xxHashValue?;
    protected _progressCallback?: (progress: number) => any | Promise<any>;
    set progressCallback(callback: (progress: number) => any | Promise<any>);
    get modPackBufferSize(): number;
    get modMetaInfo(): ModMeta;
    get hash(): bigint;
    get hashString(): string;
    checkHash(modPackBuffer: Uint8Array): Promise<boolean>;
    load(modPackBuffer: Uint8Array, password?: string): Promise<ModMeta>;
    getFileList(): string[];
    protected getFileByMeta(fileMeta: FileMeta, filePath: string): Promise<Uint8Array | undefined>;
    getFile(filePath: string): Promise<Uint8Array | undefined>;
    readFile(filePath: string): Promise<Uint8Array | undefined>;
    getBootJson(): Promise<Uint8Array | undefined>;
    getFileTree(): Promise<Record<string, any> | undefined>;
    get fileTreeRef(): Record<string, any> | undefined;
    checkValid(): Promise<boolean>;
}
